import type { RestaurantCandidate } from "./schemas.js";

export const FEATURED_RESTAURANTS_BARCELONA: RestaurantCandidate[] = [
  {
    id: "featured-asante-bcn",
    name: "Asante",
    address: "Carrer de Verdi, 67, Gràcia, 08012 Barcelona",
    latitude: 41.4045,
    longitude: 2.1558,
    websiteUrl: "https://www.instagram.com/asante_bcn/",
    mapUrl: "https://www.openstreetmap.org/?mlat=41.4045&mlon=2.1558#map=17/41.4045/2.1558",
    provider: "curated",
    cuisine: "brunch",
    tags: ["cafe", "brunch", "pastry", "vegan", "featured"],
    isVegan: true,
    isFeatured: true,
    rating: 4.9,
  },
  {
    id: "featured-vrutal-bcn",
    name: "Vrutal",
    address: "Rambla del Poblenou, 16, 08005 Barcelona",
    latitude: 41.3998,
    longitude: 2.2036,
    websiteUrl: "https://vrutalrestaurant.com/",
    mapUrl: "https://www.openstreetmap.org/?mlat=41.3998&mlon=2.2036#map=17/41.3998/2.2036",
    provider: "curated",
    cuisine: "burger",
    tags: ["burger", "cocktails", "comfort_food", "vegan", "featured"],
    isVegan: true,
    isFeatured: true,
    rating: 4.8,
  },
  {
    id: "featured-blubar-bcn",
    name: "Blu Bar",
    address: "Rambla del Poblenou, 11, 08005 Barcelona",
    latitude: 41.3994,
    longitude: 2.2041,
    websiteUrl: "https://blubarbarcelona.com/",
    mapUrl: "https://www.openstreetmap.org/?mlat=41.3994&mlon=2.2041#map=17/41.3994/2.2041",
    provider: "curated",
    cuisine: "pizza",
    tags: ["pizza", "tapas", "cocktails", "vegan", "featured"],
    isVegan: true,
    isFeatured: true,
    rating: 4.7,
  },
  {
    id: "featured-madmadvegan-bcn",
    name: "Mad Mad Vegan",
    address: "Carrer dels Escudellers, 44, Ciutat Vella, 08002 Barcelona",
    latitude: 41.3798,
    longitude: 2.1762,
    websiteUrl: "https://madmadvegan.com/",
    mapUrl: "https://www.openstreetmap.org/?mlat=41.3798&mlon=2.1762#map=17/41.3798/2.1762",
    provider: "curated",
    cuisine: "burger",
    tags: ["burger", "fast_food", "tapas", "vegan", "featured"],
    isVegan: true,
    isFeatured: true,
    rating: 4.8,
  },
  {
    id: "featured-gallosanto-bcn",
    name: "Gallo Santo",
    address: "Carrer del Torrent de l'Olla, 64, Gràcia, 08012 Barcelona",
    latitude: 41.4012,
    longitude: 2.1581,
    websiteUrl: "https://gallosanto.es/",
    mapUrl: "https://www.openstreetmap.org/?mlat=41.4012&mlon=2.1581#map=17/41.4012/2.1581",
    provider: "curated",
    cuisine: "mexican",
    tags: ["mexican", "tacos", "cocktails", "vegan", "featured"],
    isVegan: true,
    isFeatured: true,
    rating: 4.7,
  },
  {
    id: "featured-desoriente-bcn",
    name: "Desoriente",
    address: "Carrer de Ramón y Cajal, 36, Gràcia, 08012 Barcelona",
    latitude: 41.4026,
    longitude: 2.1594,
    websiteUrl: "https://desoriente.com/",
    mapUrl: "https://www.openstreetmap.org/?mlat=41.4026&mlon=2.1594#map=17/41.4026/2.1594",
    provider: "curated",
    cuisine: "asian",
    tags: ["asian", "sushi", "ramen", "vegan", "featured"],
    isVegan: true,
    isFeatured: true,
    rating: 4.8,
  },
  {
    id: "featured-alive-bcn",
    name: "Alive Restaurant",
    address: "Travessera de les Corts, 180, Les Corts, 08028 Barcelona",
    latitude: 41.3852,
    longitude: 2.1311,
    websiteUrl: "https://www.aliverestaurant.es/",
    mapUrl: "https://www.openstreetmap.org/?mlat=41.3852&mlon=2.1311#map=17/41.3852/2.1311",
    provider: "curated",
    cuisine: "mediterranean",
    tags: ["mediterranean", "bistrot", "tapas", "vegan", "featured"],
    isVegan: true,
    isFeatured: true,
    rating: 4.8,
  },
  {
    id: "featured-goodshit-bcn",
    name: "Good Shit Vegan Kebabs",
    address: "Carrer del Torrent de l'Olla, 138, Gràcia, 08012 Barcelona",
    latitude: 41.4048,
    longitude: 2.1552,
    websiteUrl: "https://goodshitvegan.com/",
    mapUrl: "https://www.openstreetmap.org/?mlat=41.4048&mlon=2.1552#map=17/41.4048/2.1552",
    provider: "curated",
    cuisine: "kebab",
    tags: ["kebab", "street_food", "vegan", "featured"],
    isVegan: true,
    isFeatured: true,
    rating: 4.7,
  },
  {
    id: "featured-velada-bcn",
    name: "Velada",
    address: "Carrer dels Còdols, 13, Ciutat Vella, 08002 Barcelona",
    latitude: 41.3789,
    longitude: 2.1772,
    websiteUrl: "https://www.instagram.com/velada_bcn/",
    mapUrl: "https://www.openstreetmap.org/?mlat=41.3789&mlon=2.1772#map=17/41.3789/2.1772",
    provider: "curated",
    cuisine: "tapas",
    tags: ["tapas", "spanish", "cocktails", "vegan", "featured"],
    isVegan: true,
    isFeatured: true,
    rating: 4.8,
  },
  {
    id: "featured-bubita-bcn",
    name: "Bubita Sangria Bar",
    address: "Carrer dels Flassaders, 15, El Born, 08003 Barcelona",
    latitude: 41.3851,
    longitude: 2.1814,
    websiteUrl: "https://bubitasangriabar.com/",
    mapUrl: "https://www.openstreetmap.org/?mlat=41.3851&mlon=2.1814#map=17/41.3851/2.1814",
    provider: "curated",
    cuisine: "tapas",
    tags: ["tapas", "paella", "spanish", "vegan", "featured"],
    isVegan: true,
    isFeatured: true,
    rating: 4.6,
  },
  {
    id: "featured-hanai-bcn",
    name: "Hanai Vegana",
    address: "Carrer de Carders, 28, El Born, 08003 Barcelona",
    latitude: 41.3868,
    longitude: 2.1802,
    websiteUrl: "https://hanaivegana.com/",
    mapUrl: "https://www.openstreetmap.org/?mlat=41.3868&mlon=2.1802#map=17/41.3868/2.1802",
    provider: "curated",
    cuisine: "bakery",
    tags: ["bakery", "pastry", "gluten_free", "cafe", "vegan", "featured"],
    isVegan: true,
    isFeatured: true,
    rating: 4.9,
  },
  {
    id: "featured-laperraverde-bcn",
    name: "La Perra Verde",
    address: "Carrer de la Mare de Déu dels Desemparats, 18, Gràcia, 08012 Barcelona",
    latitude: 41.4019,
    longitude: 2.1588,
    websiteUrl: "https://www.instagram.com/laperraverdebcn/",
    mapUrl: "https://www.openstreetmap.org/?mlat=41.4019&mlon=2.1588#map=17/41.4019/2.1588",
    provider: "curated",
    cuisine: "tapas",
    tags: ["tapas", "bistrot", "vegan", "featured"],
    isVegan: true,
    isFeatured: true,
    rating: 4.7,
  },
  {
    id: "featured-morgentau-bcn",
    name: "Morgentau",
    address: "Carrer de Pujades, 162, Poblenou, 08005 Barcelona",
    latitude: 41.4009,
    longitude: 2.1989,
    websiteUrl: "https://www.instagram.com/morgentaubcn/",
    mapUrl: "https://www.openstreetmap.org/?mlat=41.4009&mlon=2.1989#map=17/41.4009/2.1989",
    provider: "curated",
    cuisine: "brunch",
    tags: ["cafe", "brunch", "bakery", "vegan", "featured"],
    isVegan: true,
    isFeatured: true,
    rating: 4.8,
  },
  {
    id: "featured-quinoa-bcn",
    name: "Quinoa Bar",
    address: "Travessia de Sant Antoni, 18, Gràcia, 08012 Barcelona",
    latitude: 41.4018,
    longitude: 2.1565,
    websiteUrl: "https://www.instagram.com/quinoabar/",
    mapUrl: "https://www.openstreetmap.org/?mlat=41.4018&mlon=2.1565#map=17/41.4018/2.1565",
    provider: "curated",
    cuisine: "burger",
    tags: ["burger", "cafe", "bowls", "vegan", "featured"],
    isVegan: true,
    isFeatured: true,
    rating: 4.7,
  },
];
