import type { RestaurantCandidate } from "@vegan-tools/domain";

/**
 * Curated list of well-known vegan and vegan-friendly restaurants in Catalonia and worldwide hubs.
 * Provides instant zero-latency map markers and saves external API quota.
 */
export const CURATED_RESTAURANTS: RestaurantCandidate[] = [
  // --- CATALUNYA: BARCELONA ---
  {
    id: "curated-bcn-teresa-carles",
    name: "Teresa Carles",
    address: "Carrer de Jovellanos, 2, 08001 Barcelona",
    latitude: 41.3855,
    longitude: 2.1685,
    websiteUrl: "https://www.teresacarles.com",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Teresa+Carles+Barcelona",
    provider: "curated",
    cuisine: "mediterranean",
    tags: ["mediterranean", "vegetarian", "gluten_free", "restaurant"],
    isVegetarian: true,
    isVegan: false,
    rating: 4.6,
  },
  {
    id: "curated-bcn-roots-vegan",
    name: "Roots Vegan",
    address: "Carrer d'Aragó, 208, 08011 Barcelona",
    latitude: 41.3892,
    longitude: 2.1584,
    websiteUrl: "https://rootsvegan.com",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Roots+Vegan+Barcelona",
    provider: "curated",
    cuisine: "burger",
    tags: ["vegan", "burger", "restaurant"],
    isVegan: true,
    isVegetarian: true,
    rating: 4.7,
  },
  {
    id: "curated-bcn-rasoterra",
    name: "Rasoterra Vegan Bistrot",
    address: "Carrer del Palau, 5, 08002 Barcelona",
    latitude: 41.3814,
    longitude: 2.1782,
    websiteUrl: "https://www.rasoterra.cat",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Rasoterra+Barcelona",
    provider: "curated",
    cuisine: "mediterranean",
    tags: ["vegan", "mediterranean", "catalan", "restaurant"],
    isVegan: true,
    isVegetarian: true,
    rating: 4.8,
  },
  {
    id: "curated-bcn-gallo-santo",
    name: "Gallo Santo",
    address: "Carrer del Torrent de l'Olla, 64, 08012 Barcelona",
    latitude: 41.4018,
    longitude: 2.1582,
    websiteUrl: "https://gallosanto.com",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Gallo+Santo+Gracia+Barcelona",
    provider: "curated",
    cuisine: "restaurant",
    tags: ["vegan", "restaurant"],
    isVegan: true,
    isVegetarian: true,
    rating: 4.5,
  },
  {
    id: "curated-bcn-vegan-junk-food",
    name: "Vegan Junk Food Bar",
    address: "Carrer de Manresa, 4, 08003 Barcelona",
    latitude: 41.3842,
    longitude: 2.1805,
    websiteUrl: "https://www.veganjunkfoodbar.com",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Vegan+Junk+Food+Bar+Barcelona",
    provider: "curated",
    cuisine: "burger",
    tags: ["vegan", "burger", "restaurant"],
    isVegan: true,
    isVegetarian: true,
    rating: 4.4,
  },
  {
    id: "curated-bcn-santoni",
    name: "Santoni Vegan Bakery & Cafe",
    address: "Ronda de Sant Antoni, 63, 08011 Barcelona",
    latitude: 41.3831,
    longitude: 2.1642,
    websiteUrl: "https://www.instagram.com/santonicafe",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Santoni+Vegan+Barcelona",
    provider: "curated",
    cuisine: "cafe_bakery",
    tags: ["vegan", "cafe_bakery", "italian"],
    isVegan: true,
    isVegetarian: true,
    rating: 4.7,
  },
  {
    id: "flax-and-kale",
    name: "Flax & Kale",
    address: "Carrer dels Tallers, 74b, 08001 Barcelona",
    latitude: 41.3858,
    longitude: 2.1656,
    websiteUrl: "https://flaxandkale.com",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Flax+and+Kale+Barcelona",
    provider: "curated",
    cuisine: "mediterranean",
    tags: ["mediterranean", "gluten_free", "cafe_bakery", "restaurant"],
    isVegetarian: true,
    isVegan: false,
    rating: 4.3,
  },

  // --- CATALUNYA: VIC & OSONA ---
  {
    id: "curated-vic-nyamera",
    name: "La Nyàmera",
    address: "Carrer de Sant Sadurní, 8, 08500 Vic",
    latitude: 41.9298,
    longitude: 2.2536,
    websiteUrl: "https://www.lanyamera.cat",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=La+Nyamera+Vic",
    provider: "curated",
    cuisine: "catalan",
    tags: ["vegan", "catalan", "mediterranean", "restaurant"],
    isVegan: true,
    isVegetarian: true,
    rating: 4.9,
  },
  {
    id: "curated-vic-el-taller",
    name: "El Taller - Espai Vegà",
    address: "Plaça Major, 12, 08500 Vic",
    latitude: 41.9304,
    longitude: 2.2547,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=El+Taller+Vic",
    provider: "curated",
    cuisine: "cafe_bakery",
    tags: ["vegan", "cafe_bakery", "restaurant"],
    isVegan: true,
    isVegetarian: true,
    rating: 4.8,
  },

  // --- CATALUNYA: GIRONA ---
  {
    id: "curated-gir-greta",
    name: "Greta",
    address: "Carrer de la Cort Reial, 26, 17004 Girona",
    latitude: 41.9863,
    longitude: 2.8252,
    websiteUrl: "https://www.restaurantgreta.com/cat/catala-carta-restaurant-greta",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Greta+Restaurant+Girona",
    provider: "curated",
    cuisine: "mediterranean",
    tags: ["vegan", "mediterranean", "catalan", "restaurant"],
    isVegan: true,
    isVegetarian: true,
    rating: 4.8,
  },
  {
    id: "curated-gir-bionectar",
    name: "Bionèctar Organic Living Food",
    address: "Carrer Francesc Ciurana, 22, 17001 Girona",
    latitude: 41.9796,
    longitude: 2.8182,
    websiteUrl: "https://www.bionectar.org",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Bionectar+Girona",
    provider: "curated",
    cuisine: "mediterranean",
    tags: ["vegan", "mediterranean", "gluten_free", "restaurant"],
    isVegan: true,
    isVegetarian: true,
    rating: 4.8,
  },
  {
    id: "curated-gir-integral",
    name: "Restaurant Vegetarià Integral",
    address: "Carrer de la Barca, 4, 17004 Girona",
    latitude: 41.9868,
    longitude: 2.8252,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Integral+Girona",
    provider: "curated",
    cuisine: "mediterranean",
    tags: ["vegetarian", "mediterranean", "catalan", "restaurant"],
    isVegetarian: true,
    isVegan: false,
    rating: 4.5,
  },

  // --- CATALUNYA: LLEIDA & TARRAGONA ---
  {
    id: "curated-tgn-el-vergel",
    name: "El Vergel Veggie Restaurant",
    address: "Carrer Major, 11, 43003 Tarragona",
    latitude: 41.1172,
    longitude: 1.2573,
    websiteUrl: "https://www.el-vergel.com",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=El+Vergel+Tarragona",
    provider: "curated",
    cuisine: "mediterranean",
    tags: ["vegan", "mediterranean", "restaurant"],
    isVegan: true,
    isVegetarian: true,
    rating: 4.7,
  },
  {
    id: "curated-lleida-hortet",
    name: "L'Hortet",
    address: "Carrer Major, 45, 25007 Lleida",
    latitude: 41.6152,
    longitude: 0.6264,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=L+Hortet+Lleida",
    provider: "curated",
    cuisine: "catalan",
    tags: ["vegetarian", "catalan", "mediterranean", "restaurant"],
    isVegetarian: true,
    isVegan: false,
    rating: 4.4,
  },

  // --- CATALUNYA: MANRESA & VALLES ---
  {
    id: "curated-manresa-espai-organic",
    name: "Espai Orgànic",
    address: "Carrer del Born, 28, 08241 Manresa",
    latitude: 41.7245,
    longitude: 1.8268,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Espai+Organic+Manresa",
    provider: "curated",
    cuisine: "cafe_bakery",
    tags: ["vegan", "cafe_bakery", "mediterranean"],
    isVegan: true,
    isVegetarian: true,
    rating: 4.6,
  },

  // --- WORLD HUBS: LONDON ---
  {
    id: "curated-lon-purezza-camden",
    name: "Purezza Camden",
    address: "43 Parkway, London NW1 7PN",
    latitude: 51.5386,
    longitude: -0.1442,
    websiteUrl: "https://purezza.co.uk",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Purezza+Camden+London",
    provider: "curated",
    cuisine: "italian",
    tags: ["vegan", "italian", "gluten_free", "restaurant"],
    isVegan: true,
    isVegetarian: true,
    rating: 4.8,
  },
  {
    id: "curated-lon-mildreds-soho",
    name: "Mildreds Soho",
    address: "45 Lexington St, London W1F 9AN",
    latitude: 51.5134,
    longitude: -0.1378,
    websiteUrl: "https://www.mildreds.co.uk",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Mildreds+Soho+London",
    provider: "curated",
    cuisine: "asian",
    tags: ["vegan", "asian", "international", "restaurant"],
    isVegan: true,
    isVegetarian: true,
    rating: 4.6,
  },

  // --- WORLD HUBS: BERLIN ---
  {
    id: "curated-ber-brammibals",
    name: "Brammibal's Plant-Based Donuts",
    address: "Maybachufer 8, 12047 Berlin",
    latitude: 52.4939,
    longitude: 13.4244,
    websiteUrl: "https://www.brammibalsdonuts.com",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Brammibals+Berlin",
    provider: "curated",
    cuisine: "cafe_bakery",
    tags: ["vegan", "cafe_bakery"],
    isVegan: true,
    isVegetarian: true,
    rating: 4.8,
  },

  // --- WORLD HUBS: PARIS ---
  {
    id: "curated-par-charlotte",
    name: "Le Potager de Charlotte",
    address: "12 Rue de la Tour d'Auvergne, 75009 Paris",
    latitude: 48.8789,
    longitude: 2.3456,
    websiteUrl: "https://www.lepotagerdecharlotte.fr",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Le+Potager+de+Charlotte+Paris",
    provider: "curated",
    cuisine: "restaurant",
    tags: ["vegan", "restaurant", "gluten_free"],
    isVegan: true,
    isVegetarian: true,
    rating: 4.9,
  },
];
