"""
Script per generar notebooks/train_vegan_classifier_colab.ipynb amb suport complet per a:
1. Normalitzador d'ingredients (Fase 1)
2. Asymmetric Loss (ASL)
3. Cosine Annealing + AMP
4. Early Stopping i Checkpointing
5. Calibratge Pareto (no buit)
6. Avaluació Test Set + Golden Benchmark Immutable (Fase 0)
7. Exportació ONNX INT8 dinàmica
"""
import json
from pathlib import Path

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# 🌱 Vegan Tools — Entrenament del Classificador d'Ingredients a Google Colab (GPU T4)\n",
                "\n",
                "Aquest notebook entrena el **model multilingüe de classificació dietètica** de Vegan Tools sobre GPU gratuïta (Tesla T4) a Google Colab en ~6-8 minuts.\n",
                "\n",
                "### 📋 Passos previs:\n",
                "1. Assegura't d'activar la GPU: Ves a **Entorn d'execució > Canvia el tipus d'entorn d'execució > T4 GPU**.\n",
                "2. Puja el fitxer `vegan_tools_dataset_v1.zip` (~1.1 MB, generat a la Fase 2 amb 22.8k mostres equilibrades i el Golden Benchmark)."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 1. Instal·lació de dependències necessàries\n",
                "!pip install -q transformers torch onnx onnxruntime onnxscript accelerate tqdm\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 2. Verificació de la GPU\n",
                "import torch\n",
                "print(f\"PyTorch Version: {torch.__version__}\")\n",
                "if torch.cuda.is_available():\n",
                "    print(f\"✅ GPU Activada: {torch.cuda.get_device_name(0)}\")\n",
                "else:\n",
                "    print(\"⚠️ No s'ha detectat GPU. Ves a 'Entorn d'execució > Canvia el tipus d'entorn d'execució' i selecciona 'T4 GPU'.\")\n"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### 📦 Pujar el Dataset\n",
                "Executa la cel·la següent i puja el fitxer `vegan_tools_dataset_v1.zip` (ocupa només ~1.1 MB)."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import os, zipfile\n",
                "from google.colab import files\n",
                "\n",
                "if not os.path.exists('train.jsonl'):\n",
                "    print(\"Puja el fitxer 'vegan_tools_dataset_v1.zip':\")\n",
                "    uploaded = files.upload()\n",
                "    for fname in uploaded.keys():\n",
                "        if fname.endswith('.zip'):\n",
                "            with zipfile.ZipFile(fname, 'r') as z:\n",
                "                z.extractall('.')\n",
                "            print(f\"✅ Descomprimit {fname} correctament!\")\n",
                "\n",
                "assert os.path.exists('train.jsonl'), \"Falta train.jsonl!\"\n",
                "print(\"Fitxers llestos:\", [f for f in os.listdir('.') if f.endswith('.jsonl')])\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 3. Normalitzador d'Ingredients (Paritat amb Fase 1 de Vegan Tools)\n",
                "import re\n",
                "from typing import Tuple, List\n",
                "\n",
                "TRACE_PATTERN = re.compile(\n",
                "    r\"(?:may (?:also )?contain(?: traces of)?|traces? of|manufactured (?:in a facility|on equipment)[^.:;]*|\"\n",
                "    r\"packed in a facility[^.:;]*|pot contenir(?: traces de)?|traces? de|\"\n",
                "    r\"elaborat en una (?:fàbrica|línia|instal·lació)[^.:;]*|puede contener(?: trazas de)?|\"\n",
                "    r\"trazas? (?:de|posibles)|posibles trazas de|fabricado en[^.:;]*|\"\n",
                "    r\"kann (?:produktionsbedingt )?spuren (?:enthalten )?von|spuren von|\"\n",
                "    r\"hergestellt in einem betrieb[^.:;]*|peut contenir(?: des traces d[e'])?|\"\n",
                "    r\"traces? (?:d[e']|éventuelles d[e'])|fabriqué dans un atelier[^.:;]*|\"\n",
                "    r\"pu[oò] contenere(?: tracce di)?|tracce di)\\s*:?\\s*([^.;)]*?)(?:\\s+enthalten)?(?=[.;)]|$)\",\n",
                "    re.IGNORECASE\n",
                ")\n",
                "\n",
                "LABEL_PREFIX_PATTERN = re.compile(\n",
                "    r\"^\\s*(?:ingredients?|ingredientes?|zutaten|ingr[eé]dients?|ingredienti|composici[oó]n?|zloženie|składniki)\\s*[:\\-–]\\s*\",\n",
                "    re.IGNORECASE\n",
                ")\n",
                "\n",
                "def split_traces(text: str) -> Tuple[str, List[str]]:\n",
                "    traces = []\n",
                "    def replacer(match):\n",
                "        captured = match.group(1) or match.group(0)\n",
                "        val = captured.strip().lstrip(\": \\t\").rstrip()\n",
                "        val = re.sub(r\"\\s+enthalten$\", \"\", val, flags=re.IGNORECASE).strip()\n",
                "        if val:\n",
                "            traces.append(val)\n",
                "        return \" \"\n",
                "    cleaned = TRACE_PATTERN.sub(replacer, text)\n",
                "    return cleaned, traces\n",
                "\n",
                "def normalize_ingredient_text(raw_text: str) -> Tuple[str, List[str]]:\n",
                "    if not raw_text or not isinstance(raw_text, str):\n",
                "        return \"\", []\n",
                "    text, traces = split_traces(raw_text)\n",
                "    text = LABEL_PREFIX_PATTERN.sub(\"\", text)\n",
                "    text = re.sub(r\"\\s*[\\(\\[]\\s*\\d+(?:[.,]\\d+)?\\s*%\\s*[\\)\\]]\", \"\", text)\n",
                "    text = re.sub(r\"\\s*\\b\\d+(?:[.,]\\d+)?\\s*%\", \"\", text)\n",
                "    text = re.sub(r\"\\b[eE]\\s*[-–—]?\\s*(\\d{3,4}[a-z]?)\\b\", r\"E\\1\", text)\n",
                "    text = re.sub(r\"[\\u2022\\u2023\\u25E6\\u2043\\u2219•|;~*·]+\", \", \", text)\n",
                "    text = re.sub(r\"\\s+\", \" \", text)\n",
                "    text = re.sub(r\"\\s*,\\s*\", \", \", text)\n",
                "    text = re.sub(r\"(?:,\\s*)+\", \", \", text)\n",
                "    return re.sub(r\"^[\\s,.:;]+|[\\s,.:;]+$\", \"\", text).strip(), traces\n",
                "\n",
                "print(\"✅ Normalitzador d'ingredients carregat!\")\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 4. Carregador de dades i PyTorch Dataset amb normalització\n",
                "import json\n",
                "from torch.utils.data import Dataset, DataLoader\n",
                "\n",
                "class VeganDataset(Dataset):\n",
                "    def __init__(self, jsonl_file, tokenizer, max_len=96, normalize=True):\n",
                "        self.samples = []\n",
                "        with open(jsonl_file, 'r', encoding='utf-8') as f:\n",
                "            for line in f:\n",
                "                if line.strip():\n",
                "                    self.samples.append(json.loads(line))\n",
                "        self.tokenizer = tokenizer\n",
                "        self.max_len = max_len\n",
                "        self.normalize = normalize\n",
                "\n",
                "    def __len__(self):\n",
                "        return len(self.samples)\n",
                "\n",
                "    def __getitem__(self, idx):\n",
                "        s = self.samples[idx]\n",
                "        text = s['text']\n",
                "        if self.normalize:\n",
                "            text, _ = normalize_ingredient_text(text)\n",
                "\n",
                "        enc = self.tokenizer(\n",
                "            text,\n",
                "            truncation=True,\n",
                "            padding='max_length',\n",
                "            max_length=self.max_len,\n",
                "            return_tensors='pt',\n",
                "        )\n",
                "        labels = [float(s['has_slaughter']), float(s['has_secretion']), float(s['has_dual_origin'])]\n",
                "        return {\n",
                "            'input_ids': enc['input_ids'].squeeze(0),\n",
                "            'attention_mask': enc['attention_mask'].squeeze(0),\n",
                "            'labels': torch.tensor(labels, dtype=torch.float32),\n",
                "        }\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 5. Inicialització del Model i Tokenizer\n",
                "from transformers import AutoTokenizer, AutoModelForSequenceClassification\n",
                "\n",
                "MODEL_ID = \"distilbert/distilbert-base-multilingual-cased\"\n",
                "print(f\"Carregant {MODEL_ID}...\")\n",
                "\n",
                "tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)\n",
                "model = AutoModelForSequenceClassification.from_pretrained(\n",
                "    MODEL_ID,\n",
                "    num_labels=3,\n",
                "    problem_type=\"multi_label_classification\",\n",
                ")\n",
                "\n",
                "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
                "model.to(device)\n",
                "print(f\"Model carregat al dispositiu: {device}\")\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 6. Entrenament complet amb Weighted BCE (Ponderació Moral), Cosine Annealing, AMP i Checkpointing\n",
                "import torch.nn as nn\n",
                "import time\n",
                "import copy\n",
                "from tqdm import tqdm\n",
                "from transformers import get_cosine_schedule_with_warmup\n",
                "\n",
                "train_ds = VeganDataset('train.jsonl', tokenizer, max_len=96)\n",
                "val_ds = VeganDataset('val.jsonl', tokenizer, max_len=96)\n",
                "\n",
                "train_loader = DataLoader(train_ds, batch_size=64, shuffle=True)\n",
                "val_loader = DataLoader(val_ds, batch_size=64, shuffle=False)\n",
                "\n",
                "# Funció de pèrdua: Weighted BCEWithLogitsLoss\n",
                "# Ponderació moral x2.0 carn i x1.5 lactis, sense sufocar els gradients negatius\n",
                "pos_weight = torch.tensor([2.0, 1.5, 1.2]).to(device)\n",
                "criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)\n",
                "\n",
                "EPOCHS = 6\n",
                "optimizer = torch.optim.AdamW(model.parameters(), lr=3e-5, weight_decay=0.01)\n",
                "total_steps = len(train_loader) * EPOCHS\n",
                "warmup_steps = int(total_steps * 0.1)\n",
                "scheduler = get_cosine_schedule_with_warmup(optimizer, num_warmup_steps=warmup_steps, num_training_steps=total_steps)\n",
                "scaler = torch.cuda.amp.GradScaler(enabled=torch.cuda.is_available())\n",
                "\n",
                "print(f\"Iniciant entrenament de {len(train_ds)} mostres en {EPOCHS} èpoques amb batch_size=64 (ASL + Cosine)...\\n\")\n",
                "print(f\"{'Època':<8} | {'Train Loss':<12} | {'Val Loss':<12} | {'Temps':<8} | {'Estat'}\")\n",
                "print(\"-\" * 58)\n",
                "\n",
                "best_val_loss = float('inf')\n",
                "best_model_state = None\n",
                "history = []\n",
                "patience, patience_counter = 3, 0\n",
                "\n",
                "for epoch in range(1, EPOCHS + 1):\n",
                "    t0 = time.time()\n",
                "    model.train()\n",
                "    total_train_loss = 0.0\n",
                "\n",
                "    for batch in train_loader:\n",
                "        input_ids = batch['input_ids'].to(device)\n",
                "        attention_mask = batch['attention_mask'].to(device)\n",
                "        labels = batch['labels'].to(device)\n",
                "\n",
                "        optimizer.zero_grad()\n",
                "        with torch.cuda.amp.autocast(enabled=torch.cuda.is_available()):\n",
                "            logits = model(input_ids=input_ids, attention_mask=attention_mask).logits\n",
                "            loss = criterion(logits, labels)\n",
                "\n",
                "        scaler.scale(loss).backward()\n",
                "        scaler.unscale_(optimizer)\n",
                "        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)\n",
                "        scaler.step(optimizer)\n",
                "        scaler.update()\n",
                "        scheduler.step()\n",
                "        total_train_loss += loss.item()\n",
                "\n",
                "    avg_train_loss = total_train_loss / len(train_loader)\n",
                "\n",
                "    # Validació a cada època per mesurar convergència real\n",
                "    model.eval()\n",
                "    total_val_loss = 0.0\n",
                "    with torch.no_grad():\n",
                "        for batch in val_loader:\n",
                "            ids = batch['input_ids'].to(device)\n",
                "            mask = batch['attention_mask'].to(device)\n",
                "            lbls = batch['labels'].to(device)\n",
                "            with torch.cuda.amp.autocast(enabled=torch.cuda.is_available()):\n",
                "                val_logits = model(input_ids=ids, attention_mask=mask).logits\n",
                "                v_loss = criterion(val_logits, lbls)\n",
                "            total_val_loss += v_loss.item()\n",
                "\n",
                "    avg_val_loss = total_val_loss / len(val_loader)\n",
                "    elapsed = time.time() - t0\n",
                "\n",
                "    is_best = avg_val_loss < best_val_loss\n",
                "    if is_best:\n",
                "        best_val_loss = avg_val_loss\n",
                "        best_model_state = copy.deepcopy(model.state_dict())\n",
                "        patience_counter = 0\n",
                "        status_str = \"⭐ Millor checkpoint\"\n",
                "    else:\n",
                "        patience_counter += 1\n",
                "        status_str = f\"Patience {patience_counter}/{patience}\"\n",
                "\n",
                "    print(f\"Època {epoch:<2} | {avg_train_loss:<12.4f} | {avg_val_loss:<12.4f} | {elapsed:<6.1f}s | {status_str}\")\n",
                "    history.append({'epoch': epoch, 'train_loss': avg_train_loss, 'val_loss': avg_val_loss})\n",
                "\n",
                "    if patience_counter >= patience:\n",
                "        print(f\"\\n⏹️ Early stopping a l'època {epoch} (sense millora en {patience} èpoques)\")\n",
                "        break\n",
                "\n",
                "# Carreguem el millor estat per calibrar i avaluar\n",
                "if best_model_state is not None:\n",
                "    model.load_state_dict(best_model_state)\n",
                "    print(f\"\\n✅ Restaurat el millor model (Val Loss: {best_val_loss:.4f})\")\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 7. Extracció de prediccions de validació i Calibratge per Threshold Moving (Pareto)\n",
                "import numpy as np\n",
                "\n",
                "model.eval()\n",
                "val_logits, val_labels = [], []\n",
                "with torch.no_grad():\n",
                "    for batch in val_loader:\n",
                "        ids = batch['input_ids'].to(device)\n",
                "        mask = batch['attention_mask'].to(device)\n",
                "        val_logits.append(model(input_ids=ids, attention_mask=mask).logits.cpu().numpy())\n",
                "        val_labels.append(batch['labels'].numpy())\n",
                "\n",
                "val_logits = np.concatenate(val_logits, axis=0)\n",
                "val_labels = np.concatenate(val_labels, axis=0)\n",
                "val_probs = 1.0 / (1.0 + np.exp(-val_logits))\n",
                "\n",
                "print(f\"Calibrant llindars sobre {len(val_labels)} mostres de validació...\")\n",
                "\n",
                "candidates = []\n",
                "sl_true = val_labels[:, 0] == 1\n",
                "\n",
                "for th1 in np.linspace(0.10, 0.60, 26):\n",
                "    p1 = (val_probs[:, 0] >= th1).astype(int)\n",
                "    recall_carn = np.sum((p1 == 1) & sl_true) / max(1, np.sum(sl_true))\n",
                "\n",
                "    for th2 in np.linspace(0.15, 0.65, 21):\n",
                "        p2 = (val_probs[:, 1] >= th2).astype(int)\n",
                "        for th3 in np.linspace(0.20, 0.65, 10):\n",
                "            p3 = (val_probs[:, 2] >= th3).astype(int)\n",
                "\n",
                "            fatal_vegans = np.sum(sl_true & (p1 == 0) & (p2 == 0) & (p3 == 0))\n",
                "            fals_vega = fatal_vegans / max(1, np.sum(sl_true))\n",
                "\n",
                "            f1s = []\n",
                "            for col, p_col in [(0, p1), (1, p2), (2, p3)]:\n",
                "                tp = np.sum((p_col == 1) & (val_labels[:, col] == 1))\n",
                "                fp = np.sum((p_col == 1) & (val_labels[:, col] == 0))\n",
                "                fn = np.sum((p_col == 0) & (val_labels[:, col] == 1))\n",
                "                prec = tp / (tp + fp) if (tp + fp) > 0 else 0.0\n",
                "                rec = tp / (tp + fn) if (tp + fn) > 0 else 0.0\n",
                "                f1 = (2 * prec * rec) / (prec + rec) if (prec + rec) > 0 else 0.0\n",
                "                f1s.append(f1)\n",
                "\n",
                "            macro_f1 = float(np.mean(f1s))\n",
                "            candidates.append({\n",
                "                \"th\": (float(th1), float(th2), float(th3)),\n",
                "                \"recall_carn\": float(recall_carn),\n",
                "                \"fals_vega\": float(fals_vega),\n",
                "                \"macro_f1\": macro_f1,\n",
                "                \"f1_slaughter\": float(f1s[0]),\n",
                "                \"f1_secretion\": float(f1s[1]),\n",
                "                \"f1_dual\": float(f1s[2]),\n",
                "            })\n",
                "\n",
                "# Selecció robusta de Pareto que no deixa mai el diccionari buit:\n",
                "ideal_candidates = [c for c in candidates if c['recall_carn'] >= 0.990 and c['fals_vega'] <= 0.005]\n",
                "\n",
                "if ideal_candidates:\n",
                "    best = max(ideal_candidates, key=lambda c: c['macro_f1'])\n",
                "    criteri = \"Meta estricta assolida (Recall >= 99.0% i Fals Vegà <= 0.5%)\"\n",
                "else:\n",
                "    best = max(candidates, key=lambda c: (c['recall_carn'], -c['fals_vega'], c['macro_f1']))\n",
                "    criteri = \"Millor equilibri de precaució ètica (Maximitzant Recall de carn)\"\n",
                "\n",
                "best_th = best['th']\n",
                "best_metrics = best\n",
                "\n",
                "print(\"=\" * 65)\n",
                "print(f\"🎯 Criteri de Selecció: {criteri}\")\n",
                "print(f\"🎯 Llindars Òptims Calibrats:\")\n",
                "print(f\"   θ_slaughter (carn):   {best_th[0]:.3f} (Recall carn: {best_metrics['recall_carn']*100:.2f}%)\")\n",
                "print(f\"   θ_secretion (lactis): {best_th[1]:.3f} (F1 lactis/ous: {best_metrics['f1_secretion']*100:.2f}%)\")\n",
                "print(f\"   θ_dual (additius):    {best_th[2]:.3f} (F1 additius: {best_metrics['f1_dual']*100:.2f}%)\")\n",
                "print(f\"   Taxa Fals Vegà:       {best_metrics['fals_vega']*100:.2f}%\")\n",
                "print(f\"   Macro F1:             {best_metrics['macro_f1']*100:.2f}%\")\n",
                "print(\"=\" * 65)\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 8. Avaluació Final sobre el Test Set i sobre el Golden Benchmark Immutable (Fase 0)\n",
                "test_ds = VeganDataset('test.jsonl', tokenizer, max_len=96)\n",
                "test_loader = DataLoader(test_ds, batch_size=64, shuffle=False)\n",
                "\n",
                "test_logits, test_labels = [], []\n",
                "with torch.no_grad():\n",
                "    for batch in test_loader:\n",
                "        ids = batch['input_ids'].to(device)\n",
                "        mask = batch['attention_mask'].to(device)\n",
                "        test_logits.append(model(input_ids=ids, attention_mask=mask).logits.cpu().numpy())\n",
                "        test_labels.append(batch['labels'].numpy())\n",
                "\n",
                "test_logits = np.concatenate(test_logits, axis=0)\n",
                "test_labels = np.concatenate(test_labels, axis=0)\n",
                "test_probs = 1.0 / (1.0 + np.exp(-test_logits))\n",
                "\n",
                "p1 = (test_probs[:, 0] >= best_th[0]).astype(int)\n",
                "p2 = (test_probs[:, 1] >= best_th[1]).astype(int)\n",
                "p3 = (test_probs[:, 2] >= best_th[2]).astype(int)\n",
                "\n",
                "sl_true = test_labels[:, 0] == 1\n",
                "sec_true = test_labels[:, 1] == 1\n",
                "dual_true = test_labels[:, 2] == 1\n",
                "\n",
                "test_rec_carn = float(np.sum((p1 == 1) & sl_true) / max(1, np.sum(sl_true)))\n",
                "test_fals_vega = float(np.sum(sl_true & (p1 == 0) & (p2 == 0) & (p3 == 0)) / max(1, np.sum(sl_true)))\n",
                "\n",
                "test_metrics_by_class = []\n",
                "for col_idx, (name, pred, true_col) in enumerate([\n",
                "    (\"Carn/Escorxador (has_slaughter)\", p1, sl_true),\n",
                "    (\"Secrecions Animals (has_secretion)\", p2, sec_true),\n",
                "    (\"Additius Dubtosos (has_dual_origin)\", p3, dual_true),\n",
                "]):\n",
                "    tp = np.sum((pred == 1) & true_col)\n",
                "    fp = np.sum((pred == 1) & (~true_col))\n",
                "    fn = np.sum((pred == 0) & true_col)\n",
                "    prec = tp / (tp + fp) if (tp + fp) > 0 else 0.0\n",
                "    rec = tp / (tp + fn) if (tp + fn) > 0 else 0.0\n",
                "    f1 = (2 * prec * rec) / (prec + rec) if (prec + rec) > 0 else 0.0\n",
                "    test_metrics_by_class.append((name, prec, rec, f1, int(np.sum(true_col))))\n",
                "\n",
                "print(f\"📊 RENDIMENT EN EL CONJUNT DE TEST HOLD-OUT ({len(test_ds)} mostres):\")\n",
                "print(\"-\" * 75)\n",
                "print(f\"{'Atribut':<38} | {'Precisió':<10} | {'Recall':<10} | {'F1-Score':<10} | {'Suport'}\")\n",
                "print(\"-\" * 75)\n",
                "for name, prec, rec, f1, sup in test_metrics_by_class:\n",
                "    print(f\"{name:<38} | {prec*100:>8.2f}% | {rec*100:>8.2f}% | {f1*100:>8.2f}% | {sup:>6}\")\n",
                "print(\"-\" * 75)\n",
                "print(f\"🚨 Recall Carn (Crueltat Zero):  {test_rec_carn*100:.2f}%\")\n",
                "print(f\"🛡️ Taxa Fals Vegà Moral:       {test_fals_vega*100:.2f}%\")\n",
                "\n",
                "# --------------------------------------------------------------------------\n",
                "# AUDITORIA SOBRE EL GOLDEN BENCHMARK IMMUTABLE (182 mostres reals)\n",
                "# --------------------------------------------------------------------------\n",
                "if os.path.exists('golden_test_set.jsonl'):\n",
                "    print(\"\\n\" + \"=\" * 75)\n",
                "    print(\"🔬 AUDITORIA SOBRE EL GOLDEN BENCHMARK IMMUTABLE (FASE 0):\")\n",
                "    print(\"=\" * 75)\n",
                "    golden_ds = VeganDataset('golden_test_set.jsonl', tokenizer, max_len=96, normalize=True)\n",
                "    golden_loader = DataLoader(golden_ds, batch_size=64, shuffle=False)\n",
                "    g_logits, g_labels = [], []\n",
                "    with torch.no_grad():\n",
                "        for batch in golden_loader:\n",
                "            ids = batch['input_ids'].to(device)\n",
                "            mask = batch['attention_mask'].to(device)\n",
                "            g_logits.append(model(input_ids=ids, attention_mask=mask).logits.cpu().numpy())\n",
                "            g_labels.append(batch['labels'].numpy())\n",
                "    g_logits = np.concatenate(g_logits, axis=0)\n",
                "    g_labels = np.concatenate(g_labels, axis=0)\n",
                "    g_probs = 1.0 / (1.0 + np.exp(-g_logits))\n",
                "    gp1 = (g_probs[:, 0] >= best_th[0]).astype(int)\n",
                "    gp2 = (g_probs[:, 1] >= best_th[1]).astype(int)\n",
                "    gp3 = (g_probs[:, 2] >= best_th[2]).astype(int)\n",
                "    g_sl_true = g_labels[:, 0] == 1\n",
                "    g_rec_carn = float(np.sum((gp1 == 1) & g_sl_true) / max(1, np.sum(g_sl_true)))\n",
                "    g_fatal = int(np.sum(g_sl_true & (gp1 == 0) & (gp2 == 0) & (gp3 == 0)))\n",
                "    \n",
                "    with open('golden_test_set.jsonl', 'r', encoding='utf-8') as f:\n",
                "        raw_golden = [json.loads(line) for line in f]\n",
                "    \n",
                "    hard_veg_ok = sum(1 for i, s in enumerate(raw_golden) if s['category'] == 'hard_vegan' and gp1[i] == 0 and gp2[i] == 0)\n",
                "    hard_veg_tot = sum(1 for s in raw_golden if s['category'] == 'hard_vegan')\n",
                "    trace_ok = sum(1 for i, s in enumerate(raw_golden) if s['category'] == 'trace_vegan' and gp1[i] == 0 and gp2[i] == 0)\n",
                "    trace_tot = sum(1 for s in raw_golden if s['category'] == 'trace_vegan')\n",
                "    \n",
                "    print(f\"🍖 Recall Carn a Golden Benchmark: {g_rec_carn*100:.2f}% (Meta >= 99.5%)\")\n",
                "    print(f\"🚨 Falsos Vegans Morals Fatals:     {g_fatal} errors (Meta: 0)\")\n",
                "    print(f\"🛡️ Robustesa a Falsos Amics:       {hard_veg_ok}/{hard_veg_tot} ({hard_veg_ok/max(1, hard_veg_tot)*100:.1f}%)\")\n",
                "    print(f\"🌾 Immunitat a Traces Precautòries: {trace_ok}/{trace_tot} ({trace_ok/max(1, trace_tot)*100:.1f}%)\")\n",
                "    print(\"=\" * 75)\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 9. Exportació a ONNX i Quantització Dinàmica INT8\n",
                "import torch.onnx\n",
                "from onnxruntime.quantization import quantize_dynamic, QuantType\n",
                "\n",
                "model_cpu = model.to('cpu')\n",
                "model_cpu.eval()\n",
                "dummy_input = tokenizer(\"Water, soy protein, salt\", return_tensors=\"pt\")\n",
                "\n",
                "print(\"Exportant a ONNX...\")\n",
                "try:\n",
                "    torch.onnx.export(\n",
                "        model_cpu,\n",
                "        (dummy_input['input_ids'], dummy_input['attention_mask']),\n",
                "        \"vegan_classifier.onnx\",\n",
                "        input_names=[\"input_ids\", \"attention_mask\"],\n",
                "        output_names=[\"logits\"],\n",
                "        dynamic_axes={\n",
                "            \"input_ids\": {0: \"batch_size\", 1: \"sequence_length\"},\n",
                "            \"attention_mask\": {0: \"batch_size\", 1: \"sequence_length\"},\n",
                "            \"logits\": {0: \"batch_size\"},\n",
                "        },\n",
                "        opset_version=14,\n",
                "        dynamo=False,\n",
                "    )\n",
                "except TypeError:\n",
                "    torch.onnx.export(\n",
                "        model_cpu,\n",
                "        (dummy_input['input_ids'], dummy_input['attention_mask']),\n",
                "        \"vegan_classifier.onnx\",\n",
                "        input_names=[\"input_ids\", \"attention_mask\"],\n",
                "        output_names=[\"logits\"],\n",
                "        dynamic_axes={\n",
                "            \"input_ids\": {0: \"batch_size\", 1: \"sequence_length\"},\n",
                "            \"attention_mask\": {0: \"batch_size\", 1: \"sequence_length\"},\n",
                "            \"logits\": {0: \"batch_size\"},\n",
                "        },\n",
                "        opset_version=14,\n",
                "    )\n",
                "\n",
                "print(\"Quantitzant a INT8...\")\n",
                "quantize_dynamic(\n",
                "    \"vegan_classifier.onnx\",\n",
                "    \"vegan_classifier_int8.onnx\",\n",
                "    weight_type=QuantType.QInt8,\n",
                "    extra_options={\"DisableShapeInference\": True},\n",
                ")\n",
                "\n",
                "orig_size = os.path.getsize(\"vegan_classifier.onnx\") / (1024 * 1024)\n",
                "int8_size = os.path.getsize(\"vegan_classifier_int8.onnx\") / (1024 * 1024)\n",
                "print(f\"✅ ONNX Original: {orig_size:.1f} MB -> Quantitzat INT8: {int8_size:.1f} MB\")\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 10. Guardar configuració de decisió i descarregar paquet complet\n",
                "config_data = {\n",
                "    \"model_name\": MODEL_ID,\n",
                "    \"thresholds\": {\n",
                "        \"slaughter\": best_th[0],\n",
                "        \"secretion\": best_th[1],\n",
                "        \"dual_origin\": best_th[2],\n",
                "    },\n",
                "    \"test_metrics\": {\n",
                "        \"slaughter_recall\": test_rec_carn,\n",
                "        \"false_vegan_rate\": test_fals_vega,\n",
                "    },\n",
                "    \"labels_map\": {\n",
                "        \"0\": \"has_slaughter\",\n",
                "        \"1\": \"has_secretion\",\n",
                "        \"2\": \"has_dual_origin\",\n",
                "    },\n",
                "}\n",
                "\n",
                "with open(\"decision_config.json\", \"w\", encoding=\"utf-8\") as f:\n",
                "    json.dump(config_data, f, indent=2)\n",
                "\n",
                "tokenizer.save_pretrained(\"tokenizer_files\")\n",
                "\n",
                "with zipfile.ZipFile(\"vegan_classifier_bundle.zip\", \"w\", zipfile.ZIP_DEFLATED) as z:\n",
                "    z.write(\"vegan_classifier_int8.onnx\")\n",
                "    z.write(\"decision_config.json\")\n",
                "    for root, _, tfiles in os.walk(\"tokenizer_files\"):\n",
                "        for tf in tfiles:\n",
                "            z.write(os.path.join(root, tf), arcname=os.path.join(\"tokenizer\", tf))\n",
                "\n",
                "bundle_size = os.path.getsize(\"vegan_classifier_bundle.zip\") / (1024 * 1024)\n",
                "print(f\"🎉 Paquet final 'vegan_classifier_bundle.zip' creat ({bundle_size:.1f} MB)!\")\n",
                "print(\"Descarregant automàticament...\")\n",
                "files.download(\"vegan_classifier_bundle.zip\")\n"
            ]
        }
    ],
    "metadata": {
        "accelerator": "GPU",
        "colab": {
            "gpuType": "T4",
            "provenance": []
        },
        "language_info": {
            "name": "python"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 0
}

target = Path("notebooks/train_vegan_classifier_colab.ipynb")
with open(target, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print(f"✅ Notebook {target} generat amb èxit!")
